---
title: "INTRODUCTION"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<center>
<h3> L'implémentation des SVM pour la détection de la fraude sur les cartes de crédit </h3></center>
<br>
<p> Dans le cadre de notre projet d’implémentation d’un nouveau modèle destiné à la détection de la fraude sur les cartes de crédit des clients, la présente application a été mise en place afin de présenter l’utilisation et la performance des SVM.<p>

<p> Les SVM ou encore Séparateur à Vaste Marge sont une classe d’algorithmes d’apprentissage initialement définis pour la discrimination c’est-à-dire la prévision d’une variable qualitative binaire. Cette méthode fait partie de la catégorie des séparateurs linéaires et a pour but de trouver l’hyperplan optimal afin d’effectuer la meilleure séparation des individus.<p>

<p> La base de données concernant les transactions des clients mise à notre disposition comportait au total 31 variables dont 28 ont été considéré comme étant des principales suites à une ACP (Analyse en composantes principales). Notre variable cible était la variable binaire Classe et indiquait si oui on non la transaction était susceptible d'être frauduleuse.<p>

<p> La présentation de notre étude tournera autour des grands points suivants:<p>
<ol style="overflow: hidden;">
  <li>Aperçu de la base de données ainsi que des variables </li>
  </ul>
  <li>Utilisation des SVM et présentation de ses performences pour la séparation des évènements </li>
  </ul>
  <li>Utilisation d'autres méthodes de machine learning et comparaison de ces dernières avec les SVM </li>
  <ul>
</ol>


